version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $vishal09be -p $azspn0705c
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t vishal09be/m_mpharmacy:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag vishal09be/m_mpharmacy:$CODEBUILD_RESOLVED_SOURCE_VERSION vishal09be/m_mpharmacy:latest
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push vishal09be/m_mpharmacy:latest
